---
-
  become: true
  become_user: root
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regexp: ^PermitRootLogin
    state: present
  name: "Disable root login"
  notify: "restart ssh"
-
  become: true
  become_user: root
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regexp: "^#?PasswordAuthentication"
    state: present
  name: "Disable password authentication"
  notify: "restart ssh"
  