---
- name: Upgrade packages
  apt: upgrade=safe
  become: yes
  become_user: root

- name: Install packages
  apt:
    name: "{{ sys_packages }}"
    state: present
    update_cache: yes
  become: yes
  become_user: root
