--- 
- 
  apt: upgrade=safe
  become: true
  become_user: root
  name: "Upgrade packages"
- 
  apt: 
    name: "{{ sys_packages }}"
    state: present
    update_cache: true
  become: true
  become_user: root
  name: "Install packages"
