---
-
  become: true
  name: "UFW - Allow SSH"
  ufw:
    name: OpenSSH
    rule: allow
-
  become: true
  name: "UFW - Deny all other incoming traffic by default"
  ufw:
    direction: incoming
    policy: deny
    state: enabled