---
-
  group:
    name: sudo
    state: present
  name: "Ensure sudo group is present"
-
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: "%sudo ALL=(ALL:ALL) ALL"
    regexp: ^%sudo
    state: present
    validate: "/usr/sbin/visudo -cf %s"
  name: "Ensure sudo group has sudo privileges"
-
  become: true
  name: "Create default user"
  user:
    groups: sudo
    name: "{{ username }}"
    password: "{{ password }}"
    shell: /bin/bash
    state: present
    update_password: always
-
  authorized_key:
    key: "{{ lookup('file', public_key) }}"
    user: "{{ username }}"
  become: true
  become_user: "{{ username }}"
  name: "Add authorized key"
  