---
-
  hosts: all
  roles:
    - common
    - ufw
    - motd
    - user
    - ssh
  user: "{{ initial_user }}"
  vars_files:
    - ./inventory/group_vars/vars.yml
    - ./inventory/group_vars/vault.yml
    